= Veigar
watertao <1059912278@qq.com>
:toc: left
:source-highlighter: coderay
:sectnums:
:sectnumlevels: 4
:icons: font

一个用于开发 RESTful 接口的脚手架，基于 spring boot。

== 快速入门

=== 新建一个 Maven 项目

----
├── myapp
|   ├── src
|   |   └── main
|   |       ├── java
|   |       |   └── com
|   |       |       └── mycompany
|   |       |           └── BootstrapApplication.java
|   |       └── resources
|   |           └── application.properties
│   └── pom.xml
----

=== pom.xml

在 pom.xml 中引入 veigar 有两种方式：

==== 继承 veigar-parent

.pom.xml
[source, xml]
----
<parent>                                <!--1-->
  <groupId>io.github.watertao</groupId>
  <artifactId>veigar-parent</artifactId>
  <version>2.1.1-SNAPSHOT</version>
</parent>
<groupId>com.mycompy</groupId>
<artifactId>myapp</artifactId>
<version>1.0.0-SNAPSHOT</version>
----
<1> 继承 `veigar-parent`

==== 依赖 veigar-core

如果项目需要依赖其他 parent，无法依赖 `veigar-parent` ，那么可以通过以下方式达到同样的效果：

.pom.xml
[source, xml]
----
<groupId>com.mycompy</groupId>
<artifactId>myapp</artifactId>
<version>1.0.0-SNAPSHOT</version>
<dependencies>
  <dependency>                          <!--1-->
    <groupId>io.github.watertao</groupId>
    <artifactId>veigar-core</artifactId>
  </dependency>
</dependencies>
<build>
  <plugins>
    <plugin>                            <!--2-->
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-maven-plugin</artifactId>
    </plugin>
  </plugins>
</build>
----
<1> 依赖 `veigar-core`
<2> 添加插件 `spring-boot-maven-plugin`

=== BootstrapApplication.java

.BootstrapApplication.java
[source, java]
----
@SpringBootApplication(
   scanBasePackages={
      "com.mycompany",                  // <1>
      "io.github.watertao.veigar"
   }
)
public class BootstrapApplication {
   public static void main(String[] args) {
      SpringApplication.run(BootstrapApplication.class, args);
   }
}
----
<1> `@SpringBootApplication` 注解中 `scanBasePackages` 需要添加自己的项目 package，以及
 `io.github.watertao.veigar` ，这会告诉 spring 去扫描位于这些 package 下的 class 以便注册 bean。

[NOTE]
====
需要注意的是，`scanBasePackages` 中自己项目的 package 需要尽量设置到公司级别，比如上例中的
`com.mycompany` ，因为这会影响到组件的扫描范围。
====

=== application.properties

.application.properties
[source, properties]
----
spring.profiles.active = dev            # <1>
app.basePackage = com.mycompany.myapp   # <2>
server.port = 8080                      # <3>
cors.allowedOrigins = *                 # <4>
----
<1> 开发环境下设置为 `dev`， 生产环境下设置为 `prod`
<2> 项目级别的 package（公司级别下一级），某些组件需要读取并使用这个参数
<3> 服务端口
<4> CORS 允许的来源

=== 第一个接口

创建 src/main/java/com/mycompany/myapp/controller/TestController.java

.TestController.java
[source, java]
----
@RestController                         // <1>
public class TestController {
    @GetMapping("/test")                // <2>
    public Object test() {
        Map map.put("a", "b");
        return map;
    }
}
----
<1> 每个 RESTful 接口类都需要使用 `@RestController` 注解
<2> 每个 RESTful 接口方法都需要使用 `@RequestMapping` 或其子注解

=== 启动项目

通过执行 `spring-boot-maven-plugin` 启动项目：

[source, shell]
----
mvn spring-boot:run
----
